language: go
sudo: required
dist: trusty

go:
  - "1.10.2"

go_import_path: github.com/kubernetes-sigs/cri-tools

before_install:
  - sudo env PATH=$PATH GOPATH=$GOPATH hack/install-cni.sh
  - sudo env PATH=$PATH GOPATH=$GOPATH hack/install-pouch.sh

install:
  - make install.tools

jobs:
  include:
    - stage: Static check
      script:
        - make lint
        - make gofmt
    - stage: Build
      script:
        - make release
    - stage: Test
      script:
        - make
        - sudo env PATH=$PATH GOPATH=$GOPATH hack/run-pouch.sh "v1alpha2"
        - sudo env PATH=$PATH GOPATH=$GOPATH hack/run-critest.sh "v1alpha2"
